### ISSUE TITLE
Add --exclude-backward-compatible to Quick Start documentation for .NET

### ISSUE THREAD

**Issue by martincostello** [MicrosoftDocs/openapi-docs#101]
The [.NET Quick start documentation](https://learn.microsoft.com/openapi/kiota/quickstarts/dotnet) gives instructions on how to create the client code:

https://github.com/MicrosoftDocs/openapi-docs/blob/7526e91367e149e052103201a42b77ff714d9ef8/OpenAPI/kiota/quickstarts/dotnet.md?plain=1#L72

This then generates the user code where the "obvious" methods to call are immediately marked as `[Obsolete]`, which is confusing and not a good first time experience.

I eventually realised I could stop all this cruft being generated by adding the `--exclude-backward-compatible` option (or `--ebc` for consistency with the others being short).

As I would have thought that most people using the Quick start documentation are generating a brand new client, I think this should be in the copy-paste-able command example to get the user started. None of the other parameters in the example are explained, so I don't think having an extra one would make any difference other than generating better initial code.

Aside: using the full flag names for the entire command would be better IMHO as then it's self-documenting.

**Comment by baywet** [comment]
Hi @martincostello 
Thanks for using kiota and for sharing your feedback.
That makes sense for new users, I'd argue then that backing store should also be included to provide them with the best experience. Which makes for a longer command.
The documentation platform supports "tips" with the format below, I'd suggest that instead of including all those in the initial command line, we add two tips (one for ebc, one for backing store) with a short abstract and a link to the full explanation.
What do you think?

Also, I think this change should be in all the quick starts, not just for dotnet.

**Comment by martincostello** [comment]
That sounds reasonable to me.

I haven't looked at any other client or their documentation, so I didn't know if the flag was relevant for any other languages or not, so if it is that makes sense to be wider scoped.

I don't know what a backing store is either, so that's something else for me to look up... 😄

**Comment by baywet** [comment]
Forgot to include the link to the [markdown reference](https://learn.microsoft.com/en-us/contribute/content/markdown-reference) in my previous reply.

Is this something you'd be willing to submit a pull request for?

**Comment by martincostello** [comment]
Do you have an example of where the content for the notes could be copied/adapted from for what you have in mind?

Adding the notes is simple, but what to write to explain them is a different matter considering my usage of Kiota so far is about 30 minutes' worth.

**Comment by baywet** [comment]
Here is an example of the general tone https://github.com/MicrosoftDocs/openapi-docs/blob/7526e91367e149e052103201a42b77ff714d9ef8/OpenAPI/kiota/quickstarts/python.md?plain=1#L52

For ebc something along the lines of 
Add --exclude-backward-compatible if you want to reduce the size of the generated client and are not concerned about potentially source breaking changes with future versions of kiota when updating the client.
