### ISSUE TITLE
Searching private respositories

### ISSUE THREAD

**Issue by matt1munich** [MicrosoftDocs/openapi-docs#108]
Regarding this page: https://learn.microsoft.com/en-us/openapi/kiota/add-api#github

It states: `Make sure the repository is public and that it has a description.`  That statement seems to be in conflict with content on this page: https://learn.microsoft.com/en-us/openapi/kiota/using#sign-in

![image](https://github.com/user-attachments/assets/4ed51b24-5725-4ecc-b8c4-cc270f12b418)

I have not been able to make `kiota search` work for private repositories.  Can you tell me if this is a supported workflow?

**Comment by baywet** [comment]
Hi @matt1munich 
Thank you for using kiota and for reaching out.
Yes this is supported, but only through the CLI, assuming you have signed in before with a PAT that has access to the private repo.
We do have an issue to document this scenario more with #3
What issue are you facing?

**Comment by matt1munich** [comment]
> Hi @matt1munich Thank you for using kiota and for reaching out. Yes this is supported, but only through the CLI, assuming you have signed in before with a PAT that has access to the private repo. We do have an issue to document this scenario more with #3 What issue are you facing?

Thank you for the quick reply!

Here is what I have done so far:
- Added `kiota-index` to the topic on the repo
- Uploaded a `apis.json` file as well as a `apis.yaml` file in the root of my repo.
- Logged into github via both device code & granular pat
- `kiota search <myorg>` returns nothing.  Also tried with `--ll DEBUG --cc` flags to try and get more info,

**Comment by baywet** [comment]
Thank you for the additional information.
One limitation from the GitHub search APIs is that it'll only search within the description of your repo and the topics, NOT the content. So you might want to tweak those to make sure the search API is actually returning it.
If you want to test it out in GitHub's UI, you can do so [here](https://github.com/search?q=topic%3Akiota-index+graph&type=repositories), making sure you're signed in, and replacing the graph keyword by something else.
Let us know if you have any additional comments or questions.

**Comment by matt1munich** [comment]
Following up:

I was able to get search working by authorizing the **Microsoft Kiota (preview)** app into my org's GitHub and allowing it to access the repositories that I would like to included in my search.

https://github.com/apps/microsoft-kiota-preview

Thank you, @baywet for the assist!
