### ISSUE TITLE
Building from source should be parameterized

### ISSUE THREAD

**Issue by baywet** [MicrosoftDocs/openapi-docs#11]
When using the following instructions on WSL, it fails as it uses the `win-x64` option. We should parameterize this setting.

https://learn.microsoft.com/en-us/openapi/kiota/install#build-from-source
Originally created by @sebastienlevert at https://github.com/microsoftdocs/openapi-docs-pr/issues/22

**Comment by nagarajDeveloper** [comment]
I think RID is already parameterized with keyword "-r".  But as in document it is directly mentioned for win-x64 it might lead confusion for non-windows platform users. To be more specific platform use case, updated document with RID values explicitly, with pull request : https://github.com/MicrosoftDocs/openapi-docs/pull/25

**Comment by nagarajDeveloper** [comment]
Hi All,

I see that #11<https://github.com/MicrosoftDocs/openapi-docs/issues/11> Closed as completed via #25<https://github.com/MicrosoftDocs/openapi-docs/pull/25>. But I didn't see latest changes at site https://learn.microsoft.com/en-us/openapi/kiota/install
[https://opengraph.githubassets.com/4250f3e4ce1a8f99007f413890c9d8a3ca179248174efb3ce0179024e48d65f9/MicrosoftDocs/openapi-docs/issues/11]<https://github.com/MicrosoftDocs/openapi-docs/issues/11>
Building from source should be parameterized · Issue #11 · MicrosoftDocs/openapi-docs<https://github.com/MicrosoftDocs/openapi-docs/issues/11>
When using the following instructions on WSL, it fails as it uses the win-x64 option. We should parameterize this setting. https://learn.microsoft.com/en-us/openapi/kiota/install#build-from-source ...
github.com

Is there anything pending yet ?

Regards,
Nagaraj

________________________________

**Comment by baywet** [comment]
@jasonjoh when you have a couple of minutes, can you trigger a refresh please?

**Comment by jasonjoh** [comment]
Done. Changes should show up in a few minutes.
