### ISSUE TITLE
adds documentation for the access type parameter

### ISSUE THREAD

**Issue by baywet** [MicrosoftDocs/openapi-docs#112]
https://github.com/microsoft/kiota/pull/5284 adds support for controlling the access modifier in CSharp.
We should document this new parameter on this page. https://github.com/MicrosoftDocs/openapi-docs/blob/a8cf5e9a2a0ebddbf9c3057a38995ef85f4d9d72/OpenAPI/kiota/using.md?plain=1#L194

CC @NKnusperer if you want to take this on as well.

**Comment by frankandrea221** [comment]
<button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textNeutral MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorNeutral MuiButton-disableElevation MuiButton-root MuiButton-text MuiButton-textNeutral MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorNeutral MuiButton-disableElevation  muiltr-16rlj66" tabindex="0" type="button" data-test="header-language-drop-down">
