### ISSUE TITLE
The API Key authentication provider is missing information about the parameter name and encoding

### ISSUE THREAD

**Issue by baywet** [MicrosoftDocs/openapi-docs#16]
https://learn.microsoft.com/en-us/openapi/kiota/authentication?tabs=go#api-key-authentication-provider

This should also document the fact that the name of the header or query parameter is configurable.

As well as the fact that it doesn't do any encoding (e.g. auth basic) on the name or the value.

Initially reported https://github.com/microsoft/kiota/issues/3041

**Comment by sebastienlevert** [comment]
We should have code examples for every language for every type of Auth.
