### ISSUE TITLE
Document the versioning of the Kiota VS Code extension 

### ISSUE THREAD

**Issue by RabebOthmani** [MicrosoftDocs/openapi-docs#18]
Add a section to https://learn.microsoft.com/en-us/openapi/kiota/support to clarify how we version the extension

**Comment by baywet** [comment]
@sebastienlevert do you remember what we wanted to add here? I can't recall.

**Comment by sebastienlevert** [comment]
Maybe with the way we do the 1.14.0000000000001 and why? I think we can ignore for now. I'll close.
