### ISSUE TITLE
add documentation on how to configure ASP.NET dependency injection for kiota client

### ISSUE THREAD

**Issue by baywet** [MicrosoftDocs/openapi-docs#37]
initially reported here https://github.com/microsoft/kiota-samples/issues/2104

**Comment by svrooij** [comment]
@baywet I've just build a complete example on how to use Kiota with Dependency Injection. https://github.com/svrooij/KiotaWithDependencyInjection

**Comment by baywet** [comment]
Thanks for putting this together! Do you think you'd be up to create a new tutorial (ASP.NET), under a new "Use kiota clients with dependency injection" category, a little like this one?
https://learn.microsoft.com/en-us/openapi/kiota/tutorials/dotnet-azure?tabs=portal

**Comment by svrooij** [comment]
@baywet Yes I do, but I would need some pointers on where to put it and how it works with code samples. Can you help me out with that?

**Comment by baywet** [comment]
Sure!
The source for the tutorial I used as an example is [here](https://github.com/MicrosoftDocs/openapi-docs/blob/0d7d8cb31729b229241371454eb15dad0fd4e3e3/OpenAPI/kiota/tutorials/dotnet-azure.md?plain=1#L2)
You could start off by creating a copy and naming it "aspnet-dependencyinjection.md"

Then we'll also need a matching entry [here](https://github.com/MicrosoftDocs/openapi-docs/blob/0d7d8cb31729b229241371454eb15dad0fd4e3e3/OpenAPI/kiota/toc.yml#L30)

Do you have additional questions?
@jasonjoh to correct me if my guidance was off.

**Comment by svrooij** [comment]
@baywet I was trying to start with it and found the the uses pointers to external code samples. Where are they located and is it also allowed to just include the code for the samples in a markdown code block?

https://github.com/MicrosoftDocs/openapi-docs/blob/0d7d8cb31729b229241371454eb15dad0fd4e3e3/OpenAPI/kiota/tutorials/dotnet-azure.md?plain=1#L57

**Comment by baywet** [comment]
This is driven by [this configuration](https://github.com/MicrosoftDocs/openapi-docs/blob/7344f15e6927381a0a6c61bf5c23d6dc14efbac5/.openpublishing.publish.config.json#L38) and ultimately points to [this file](https://github.com/microsoft/kiota-samples/blob/main/get-started/azure-auth/get-me.yml)

I'd say we'd have a preference aligning with this approach this way:
- people can grab the project
- we can setup dependabot to update the dependencies
- we can setup CI to check things still build as we update the dependencies

what do you think?
