### ISSUE TITLE
Every ADR should have a corresponding article / paragraph / something in our Docs

### ISSUE THREAD

**Issue by sebastienlevert** [MicrosoftDocs/openapi-docs#44]
https://github.com/microsoft/kiota/issues?q=label%3AADR+is%3Aclosed

**Comment by baywet** [comment]
Opened: #70, #71, #72

Everything before the date of this comment has been documented besides:
- [ ] https://github.com/microsoft/kiota/issues/3566
- [ ] https://github.com/microsoft/kiota/issues/2367
- [ ] https://github.com/microsoft/kiota/issues/2085
