### ISSUE TITLE
replace cspell ci check by acrolinx

### ISSUE THREAD

**Issue by baywet** [MicrosoftDocs/openapi-docs#88]
Both from a security standpoint and to improve the experience of editing the documentation, we want to remove the cspell ci check and replace it by [acrolinx](https://github.com/microsoftgraph/microsoft-graph-docs/pull/24290#issuecomment-2103151671)

source https://github.com/MicrosoftDocs/openapi-docs/pull/82

**Comment by baywet** [comment]
created a ticket https://dev.azure.com/msft-skilling/Content/_workitems/edit/256528

**Comment by jasonjoh** [comment]
> created a ticket https://dev.azure.com/msft-skilling/Content/_workitems/edit/256528

I'm working directly with internal folks on this

**Comment by jasonjoh** [comment]
Fixed. Note however Acrolinx does not run in this public mirror.

**Comment by baywet** [comment]
Thanks for fixing this! What are we supposed to do then? review/merge here, see the results we get from the sync PR, and correct things further if the changes don't meet the quality bar?

**Comment by jasonjoh** [comment]
Yes, that's right. This is beyond our control unfortunately.
